version: '3.8'

# TODO: Add postgres
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: uvicorn main:app --reload --port 8000

  db:
    image: postgres
    container_name: postgres
    environment:
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - 80:80
    environment:      
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin        

volumes:
  db_data:
  pgadmin_data: